openapi: 3.0.1
info:
  title: Matrix Client-Server Registration and Login API
  version: 1.0.0
servers:
  - url: 'https://matrix.org/_matrix/client/r0'
paths:

  # Session management
  /login:
    get:
      tags:
        - Session management
      summary: Get the supported login types to authenticate users
      description: Gets the homeserver's supported login types to authenticate users Clients should pick one of these and supply it as the ``type`` when logging in.
      operationId: get_login_flows
      responses:
        '200':
          description: The login types the homeserver supports
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_login_get'
              example:
                flows:
                  - type: m.login.password
        '429':
          description: This request was rate-limited.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate_limited'
    post:
      tags:
        - Session management
      summary: Authenticates the user.
      description: 'Authenticates the user, and issues an access token they can use to authorize themself in subsequent requests. If the client does not supply a `device_id`, the server must auto-generate one. The returned access token must be associated with the `device_id` supplied by the client or generated by the server. The server may invalidate any access token previously associated with that device. See `Relationship between access tokens and devices`.'
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_request_body'
        required: true
      responses:
        '200':
          description: The user has been authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_login_put'
              example:
                user_id: '@cheeky_monkey:matrix.org'
                access_token: abc123
                device_id: GHTYAJCE
        '400':
          description: 'Part of the request was invalid. For example, the login type may not be recognised.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                errcode: M_UNKNOWN
                error: Bad login type.
        '403':
          description: 'The login attempt failed. For example, the password may have been incorrect.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                errcode: M_FORBIDDEN
        '429':
          description: This request was rate-limited.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate_limited'
 
  /logout:
    post:
      tags:
        - Session management
      summary: Invalidates a user access token
      description: Invalidates an existing access token, so that it can no longer be used for\nauthorization.
      operationId: logout
      responses:
        200:
          description: The access token used in the request was succesfully invalidated.

      security:
        - accessToken: []

  /logout/all: 
    post:
      tags:
        - Session management
      description: Invalidates all access tokens for a user, so that they can no longer be used for\nauthorization. This includes the access token that made this request. \n\nThis endpoint does not require UI authorization because UI authorization is\ndesigned to protect against attacks where the someone gets hold of a single access\ntoken then takes over the account. This endpoint invalidates all access tokens for\nthe user, including the token used in the request, and therefore the attacker is\nunable to take over the account in this way.
      operationId: logout_all
      responses:
        200:
          description: The user's access tokens were succesfully invalidated.
      security:
        - accessToken: []



  # End-to-end encryption APIs
  /keys/upload:
    post:
      tags:
        - End-to-end encryption
      summary: Upload end-to-end encryption keys.
      description: Publishes end-to-end encryption keys for the device.
      operationId: uploadKeys
      requestBody:
        description: The keys to be published
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/keys_upload'
        required: false
      responses:
        '200':
          description: The provided keys were sucessfully uploaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_keys_upload'
      security:
        - accessToken: []

  /keys/query:
    post:
      tags:
        - End-to-end encryption
      summary: Download device identity keys.
      description: Returns the current devices and identity keys for the given users.
      operationId: queryKeys
      requestBody:
        description: Query defining the keys to be downloaded
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/query_keys'
        required: false
      responses:
        '200':
          description: The device information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_query_keys'
      security:
        - accessToken: []
        
  /keys/changes:
    get:
      tags: 
        - End-to-end encryption
      summary: Query users with recent device key updates.
      description: Gets a list of users who have updated their device identity keys since a\nprevious sync token.\n\nThe server should include in the results any users who:\n\n* currently share a room with the calling user (ie, both users have\n  membership state ``join``); *and*\n* added new device identity keys or removed an existing device with\n  identity keys, between ``from`` and ``to``.
      operationId: getKeysChanges
      security:
        - accessToken: []
      parameters:
        - description:  The desired start point of the list. Should be the ``next_batch`` field\nfrom a response to an earlier call to |/sync|. Users who have not\nuploaded new device identity keys since this point, nor deleted\nexisting devices with identity keys since then, will be excluded\nfrom the results.
          in: query
          name: from
          required: true
          schema:
            type: string
        - description: The desired end point of the list. Should be the ``next_batch``\nfield from a recent call to |/sync| - typically the most recent\nsuch call. This may be used by the server as a hint to check its\ncaches are up to date.
          in: query
          name: to
          required: true
          schema:  
            type: string
      responses: 
        200: 
          description: The list of users who updated their devices.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_getKeysChanges'

  /keys/claim:
    post:
      tags:
      - End-to-end encryption
      summary: Claim one-time encryption keys.
      description: Claims one-time keys for use in pre-key messages.
      operationId: claimKeys
      requestBody:
        description: Query defining the keys to be claimed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/claimKeys_request_body"
      responses:
        200:
          description: The claimed keys
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/200_claimKeys"
      security:
      - accessToken: []




  /sendToDevice/{eventType}/{txnId}:
    put:
      tags:
        - Send-to-Device messaging
      summary: Send an event to a given set of devices.
      description: This endpoint is used to send send-to-device events to a set of client devices.
      operationId: sendToDevice
      parameters:
        - name: eventType
          in: path
          description: The type of event to send.
          required: true
          schema:
            type: string
          example:
            - m.new_device
        - name: txnId
          in: path
          description: The transaction ID for this event. Clients should generate an ID unique across requests with the same access token; it will be used by the server to ensure idempotency of requests.
          required: true
          schema:
            type: string
          example: '35'
      requestBody:
        content:
          application/json:
            schema:
              title: send_to_device_request_body
              type: object
              additionalProperties:
                type: object
                description: The messages to send. A map from user ID, to a map from device ID to message body. The device ID may also be `*`, meaning all known devices for the user.
                additionalProperties:
                  $ref: "#/components/schemas/EventContent"
              
        required: true
      responses:
        '200':
          description: The message was successfully sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_void'
      security:
        - accessToken: []
        
    
  /rooms/{roomId}/send/{eventType}/{txnId}:
    put:
      tags:
        - Room participation
      summary: Send a message event to the given room.
      description: |-
        This endpoint is used to send a message event to a room. Message events
        allow access to historical events and pagination, making them suited
        for "once-off" activity in a room.
        The body of the request should be the content object of the event; the
        fields in this object will vary depending on the type of event. See
        `Room Events`_ for the m. event specification.
      operationId: sendEventTxnid
      parameters:
        - name: roomId
          in: path
          description: The room to look up the state in.
          required: true
          schema:
            type: string
          example: '!636q39766251:example.com'
        - name: eventType
          in: path
          description: The type of event.
          required: true
          schema:
            type: string
          example:
            - m.room.name
        - name: txnId
          in: path
          description: The transaction ID for this event. Clients should generate an ID unique across requests with the same access token; it will be used by the server to ensure idempotency of requests.
          required: true
          schema:
            type: string
          example: '35'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sendEventTxnid_body"
              
        required: false
      responses:
        '200':
          description: An ID for the sent event.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200_sendEventTxnid'
      security:
        - accessToken: []
  
  
        
  /sync:
    get:
      tags:
        - Room participation
      summary: Synchronise the client's state and receive new messages.
      description: 'Synchronise the client''s state with the latest state on the server. Clients use this API when they first log in to get an initial snapshot of the state on the server, and then continue to call this API to get incremental deltas to the state, and to receive new messages.'
      operationId: sync
      parameters:
        - name: filter
          in: query
          description: |-
            The ID of a filter created using the filter API or a filter JSON
            object encoded as a string. The server will detect whether it is
            an ID or a JSON object by whether the first character is a ``"{"``
            open brace. Passing the JSON inline is best suited to one off
            requests. Creating a filter using the filter API is recommended for
            clients that reuse the same filter multiple times, for example in
            long poll requests.
          schema:
            type: string
          example: 66696p746572
        - name: since
          in: query
          description: A point in time to continue a sync from.
          schema:
            type: string
          example: s72594_4483_1934
        - name: full_state
          in: query
          description: |-
            Controls whether to include the full state for all rooms the user
            is a member of.

            If this is set to `true`, then all state events will be returned,
            even if `since` is non-empty. The timeline will still be limited
            by the `since` parameter. In this case, the ``timeout`` parameter
            will be ignored and the query will return immediately, possibly with
            an empty timeline.

            If `false`, and `since` is non-empty, only state which has
            changed since the point indicated by `since` will be returned.

            By default, this is `false`.
          schema:
            type: boolean
            default: false
          example: 'false'
        - name: set_presence
          in: query
          description: |-
            Controls whether the client is automatically marked as online by
            polling this API. If this parameter is omitted then the client is
            automatically marked as online when it uses this API. Otherwise if
            the parameter is set to "offline" then the client is not marked as
            being online when it uses this API. When set to "unavailable", the
            client is marked as being idle.
          schema:
            type: string
            enum:
              - offline
              - online
              - unavailable
          example: offline
        - name: timeout
          in: query
          description: |-
            The maximum time to wait, in milliseconds, before returning this
            request. If no events (or other data) become available before this
            time elapses, the server will return a response with empty fields.

            By default, this is ``0``, so the server will return immediately
            even if the response is empty.
          schema:
            default: 0
            type: integer
          example: 30000
      security:
        - accessToken: []
      responses:
        '200':
          description: The initial snapshot or delta for the client to use to update their state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sync_response'
              example:
                next_batch: s72595_4483_1934
                presence:
                  events:
                    - sender: '@alice:example.com'
                      type: m.presence
                      content:
                        presence: online
                account_data:
                  events:
                    - type: org.example.custom.config
                      content:
                        custom_config_key: custom_config_value
                rooms:
                  join:
                    '!726s6s6q:example.com':
                      state:
                        events:
                          - sender: '@alice:example.com'
                            type: m.room.member
                            state_key: '@alice:example.com'
                            content:
                              membership: join
                            origin_server_ts: 1417731086795
                            event_id: '$66697273743031:example.com'
                      timeline:
                        events:
                          - sender: '@bob:example.com'
                            type: m.room.member
                            state_key: '@bob:example.com'
                            content:
                              membership: join
                            prev_content:
                              membership: invite
                            origin_server_ts: 1417731086795
                            event_id: '$7365636s6r6432:example.com'
                          - sender: '@alice:example.com'
                            type: m.room.message
                            txn_id: '1234'
                            content:
                              body: I am a fish
                              msgtype: m.text
                            origin_server_ts: 1417731086797
                            event_id: '$74686972643033:example.com'
                        limited: true
                        prev_batch: t34-23535_0_0
                      ephemeral:
                        events:
                          - type: m.typing
                            content:
                              user_ids:
                                - '@alice:example.com'
                      account_data:
                        events:
                          - type: m.tag
                            content:
                              tags:
                                work:
                                  order: 1
                          - type: org.example.custom.room.config
                            content:
                              custom_config_key: custom_config_value
                  invite:
                    '!696r7674:example.com':
                      invite_state:
                        events:
                          - sender: '@alice:example.com'
                            type: m.room.name
                            state_key: ''
                            content:
                              name: My Room Name
                          - sender: '@alice:example.com'
                            type: m.room.member
                            state_key: '@bob:example.com'
                            content:
                              membership: invite
                  leave: {}

components:
  schemas:
    user_identifier:
      title: User identifier
      required:
        - type
      type: object
      properties:
        type:
          type: string
          description: The type of identification.  See `Identifier types`_ for supported values and additional property descriptions.
        user:
          type: string
          description: 'The fully qualified user ID or just local part of the user ID, to log in.  Deprecated in favour of ``identifier``.'
      description: Identification information for a user
    rate_limited:
      required:
        - errcode
      type: object
      properties:
        errcode:
          type: string
          description: The M_LIMIT_EXCEEDED error code
          example: M_LIMIT_EXCEEDED
        error:
          type: string
          description: A human-readable error message.
          example: Too many requests
        retry_after_ms:
          type: integer
          description: |-
            The amount of time in milliseconds the client should wait
            before trying the request again.
          example: 2000
      description: The rate limit was reached for this request

    claimKeys_request_body:
      type: object
      properties:
        one_time_keys:
          type: object
          description: The keys to be claimed. A map from user ID, to a map from device ID to algorithm name.
          additionalProperties:
            type: object
            additionalProperties:
              type: string
              description: algorithm
              example: signed_curve25519
          example:
            '@alice:example.com':
              JLAFKJWSCS: signed_curve25519
        timeout:
          type: integer
          description: The time (in milliseconds) to wait when downloading keys from remote servers. 10 seconds is the recommended default.
          example: 10000
      required:
        - one_time_keys



    login_request_body:
      required:
        - type
      type: object
      properties:
        type:
          type: string
          description: The login type being used.
          enum:
            - m.login.password
            - m.login.token
        identifier:
          $ref: '#/components/schemas/user_identifier'
        medium:
          type: string
          description: 'When logging in using a third party identifier, the medium of the identifier. Must be ''email''.  Deprecated in favour of ``identifier``.'
        address:
          type: string
          description: Third party identifier for the user.  Deprecated in favour of ``identifier``.
        password:
          type: string
          description: |-
            Required when ``type`` is ``m.login.password``. The user's
            password.
        token:
          type: string
          description: Required when ``type`` is ``m.login.token``. Part of `Token-based`_ login.
        device_id:
          type: string
          description: |-
            ID of the client device. If this does not correspond to a
            known client device, a new device will be created. The server
            will auto-generate a device_id if this is not specified.
        initial_device_display_name:
          type: string
          description: |-
            A display name to assign to the newly-created device. Ignored
            if ``device_id`` corresponds to a known device.
      example:
        type: m.login.password
        identifier:
          type: m.id.user
          user: cheeky_monkey
        password: ilovebananas
        initial_device_display_name: Jungle Phone
    error:
      required:
        - errcode
      type: object
      properties:
        errcode:
          type: string
          description: An error code.
          example: M_UNKNOWN
        error:
          type: string
          description: A human-readable error message.
          example: An unknown error occurred
      description: A Matrix-level Error
    device_keys:
      title: DeviceKeys
      type: object
      description: Device identity keys
      properties:
        user_id:
          type: string
          description: The ID of the user the device belongs to. Must match the user ID used when logging in.
          example: '@alice:example.com'
        device_id:
          type: string
          description: The ID of the device these keys belong to. Must match the device ID used when logging in.
          example: JLAFKJWSCS
        algorithms:
          type: array
          description: The encryption algorithms supported by this device.
          items:
            type: string
          example:
            - m.olm.curve25519-aes-sha256
            - m.megolm.v1.aes-sha
        keys:
          type: object
          additionalProperties:
            type: string
          description: 'Public identity keys. The names of the properties should be in the format `<algorithm>:<device_id>`. The keys themselves should be encoded as specified by the key algorithm.'
          example:
            'curve25519:JLAFKJWSCS': 3C5BFWi2Y8MaVvjM8M22DBmh24PmgR0nPvJOIArzgyI
            'ed25519:JLAFKJWSCS': lEuiRJBit0IG6nUf5pUzWTUEsRVVe/HJkoKuEww9ULI
        signatures:
          type: object
          description: 'Signatures for the device key object. A map from user ID, to a map from `<algorithm>:<device_id>` to the signature. The signature is calculated using the process described at `Signing JSON`.'
          additionalProperties:
            type: object
            additionalProperties:
              type: string
          example:
            '@alice:example.com':
              'ed25519:JLAFKJWSCS': dSO80A01XiigH3uBiDVx/EjzaoycHcjq9lfQX0uWsqxl2giMIiSPR8a4d291W1ihKJL/a+myXS367WT6NAIcBA
        unsigned:
          $ref: '#/components/schemas/UnsignedDeviceInfo'
      required:
        - algorithms
        - device_id
        - keys
        - signatures
        - user_id
    UnsignedDeviceInfo:
      type: object
      description: 'Additional data added to the device key information by intermediate servers, and not covered by the signatures.'
      properties:
        device_display_name:
          type: string
          description: The display name which the user set on the device.
    keys_upload:
      type: object
      properties:
        device_keys:
          type: object
          description: Identity keys for the device. May be absent if no new identity keys are required.
          properties:
            user_id:
              type: string
            device_id:
              type: string
            algorithms:
              type: array
              items:
                type: string
            keys:
              type: object
              additionalProperties:
                type: string
            signatures:
              type: object
              additionalProperties:
                type: object
                additionalProperties:
                  type: string
        one_time_keys:
          type: object
          properties: {}
          description: 'One-time public keys for `pre-key` messages. The names of the properties should be in the format `<algorithm>:<key_id>`. The format of the key is determined by the key algorithm. May be absent if no new one-time keys are required.'
          example:
            'curve25519:AAAAAQ': /qyvZvwjiTxGdGU0RCguDCLeR+nmsb3FfNG3/Ve4vU8
            'signed_curve25519:AAAAHg':
              key: zKbLg+NrIjpnagy+pIY6uPL4ZwEG2v+8F9lmgsnlZzs
              signatures:
                '@alice:example.com':
                  'ed25519:JLAFKJWSCS': FLWxXqGbwrb8SM3Y795eB6OA8bwBcoMZFXBqnTn58AYWZSqiD45tlBVcDa2L7RwdKXebW/VzDlnfVJ+9jok1Bw
            'signed_curve25519:AAAAHQ':
              key: j3fR3HemM16M7CWhoI4Sk5ZsdmdfQHsKL1xuSft6MSw
              signatures:
                '@alice:example.com':
                  'ed25519:JLAFKJWSCS': IQeCEPb9HFk217cU9kw9EOiusC6kMIkoIRnbnfOh5Oc63S1ghgyjShBGpu34blQomoalCyXWyhaaT3MrLZYQAA
    query_keys:
      type: object
      properties:
        timeout:
          type: integer
          description: The time (in milliseconds) to wait when downloading keys from remote servers. 10 seconds is the recommended default.
          example: 10000
        device_keys:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
              description: device ID
          description: 'The keys to be downloaded. A map from user ID, to a list of device IDs, or to an empty list to indicate all devices for the corresponding user.'
          example:
            '@alice:example.com': []
        token:
          type: string
          description: 'If the client is fetching keys as a result of a device update received in a sync request, this should be the ''since'' token of that sync request, or any later sync token. This allows the server to ensure its response contains the keys advertised by the notification in that sync.'
      required:
        - device_keys
    200_void: {}
    200_login_get:
      type: object
      properties:
        flows:
          type: array
          description: The homeserver's supported login types
          items:
            title: LoginFlow
            type: object
            properties:
              type:
                type: string
                description: The login type. This is supplied as the ``type`` when logging in.
    200_login_put:
      type: object
      properties:
        user_id:
          type: string
          description: The fully-qualified Matrix ID that has been registered.
        access_token:
          type: string
          description: |-
            An access token for the account.
            This access token can then be used to authorize other requests.
        home_server:
          type: string
          description: |-
            The server_name of the homeserver on which the account has
            been registered.
            **Deprecated**. Clients should extract the server_name from
            ``user_id`` (by splitting at the first colon) if they require
            it. Note also that ``homeserver`` is not spelt this way.
        device_id:
          type: string
          description: |-
            ID of the logged-in device. Will be the same as the
            corresponding parameter in the request, if one was specified. 
    200_keys_upload:
      type: object
      properties:
        one_time_key_counts:
          description: 'For each key algorithm, the number of unclaimed one-time keys of that type currently held on the server for this device.'
          type: object
          additionalProperties:
            type: integer
          example:
            curve25519: 10
            signed_curve25519: 20
      required:
        - one_time_key_counts
    200_query_keys:
      type: object
      properties:
        failures:
          description: 'If any remote homeservers could not be reached, they are recorded here. The names of the properties are the names of the unreachable servers. If the homeserver could be reached, but the user or device was unknown, no failure is recorded. Instead, the corresponding user or device is missing from the `device_keys` result.'
          type: object
          additionalProperties:
            type: object
            properties: {}
        device_keys:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/device_keys'
          description: 'Information on the queried devices. A map from user ID, to a map from device ID to device information.  For each device, the information returned will be the same as uploaded via ``/keys/upload``, with the addition of an ``unsigned`` property.'
          example:
            '@alice:example.com':
              JLAFKJWSCS:
                user_id: '@alice:example.com'
                device_id: JLAFKJWSCS
                algorithms:
                  - m.olm.v1.curve25519-aes-sha256
                  - m.megolm.v1.aes-sha
                keys:
                  'curve25519:JLAFKJWSCS': 3C5BFWi2Y8MaVvjM8M22DBmh24PmgR0nPvJOIArzgyI
                  'ed25519:JLAFKJWSCS': lEuiRJBit0IG6nUf5pUzWTUEsRVVe/HJkoKuEww9ULI
                signatures:
                  '@alice:example.com':
                    'ed25519:JLAFKJWSCS': dSO80A01XiigH3uBiDVx/EjzaoycHcjq9lfQX0uWsqxl2giMIiSPR8a4d291W1ihKJL/a+myXS367WT6NAIcBA
                unsigned:
                  device_display_name: Alice's mobile phone
                  
    sendEventTxnid_body:
      type: object
      example:
        msgtype: m.text
        body: hello
      
    200_sendEventTxnid:
      type: object
      properties:
        event_id:
          type: string
          description: A unique identifier for the event.
      example:
        event_id: '$YUwRidLecu:example.com'
        
    200_getKeysChanges:
      type: object
      properties:
        changed:
          description: The Matrix User IDs of all users who updated their device\nidentity keys.
          type: array
          items:
            type: string
          example:
            - "@alice:example.com"
            - "@bob:example.org"
        left:
          description: The Matrix User IDs of all users who may have left all\nthe end-to-end encrypted rooms they previously shared\nwith the user.
          type: array
          items:
            type: string
          example:
            - "@clara:example.com"
            - "@doug:example.org"

    
    200_claimKeys:
      type: object
      properties:
        failures:
          type: object
          additionalProperties:
            type: object
            properties: {}
          description: |-
            If any remote homeservers could not be reached, they are
            recorded here. The names of the properties are the names of
            the unreachable servers.

            If the homeserver could be reached, but the user or device
            was unknown, no failure is recorded. Instead, the corresponding
            user or device is missing from the ``one_time_keys`` result.
          example: {}
        one_time_keys:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
              properties: {}
          description: |-
            One-time keys for the queried devices. A map from user ID, to a
            map from devices to a map from ``<algorithm>:<key_id>`` to the key object.
          example:
            '@alice:example.com':
              JLAFKJWSCS:
                signed_curve25519:AAAAHg:
                  key: zKbLg+NrIjpnagy+pIY6uPL4ZwEG2v+8F9lmgsnlZzs
                  signatures:
                    '@alice:example.com':
                      ed25519:JLAFKJWSCS: FLWxXqGbwrb8SM3Y795eB6OA8bwBcoMZFXBqnTn58AYWZSqiD45tlBVcDa2L7RwdKXebW/VzDlnfVJ+9jok1Bw
  
  
    sync_rooms:
      title: Rooms
      type: object
      description: Updates to rooms.
      properties:
        join:
          $ref: '#/components/schemas/sync_rooms_join'
        invite:
          $ref: '#/components/schemas/sync_rooms_invite'
        leave:
          $ref: '#/components/schemas/sync_rooms_leave'
    sync_rooms_join:
      title: Joined Rooms
      type: object
      description: The rooms that the user has joined.
      additionalProperties:
        title: Joined Room
        type: object
        properties:
          state:
            title: State
            type: object
            description: |-
              Updates to the state, between the time indicated by
              the ``since`` parameter, and the start of the
              ``timeline`` (or all state up to the start of the
              ``timeline``, if ``since`` is not given, or
              ``full_state`` is true).

              N.B. state updates for ``m.room.member`` events will
              be incomplete if ``lazy_load_members`` is enabled in
              the ``/sync`` filter, and only return the member events
              required to display the senders of the timeline events
              in this response.
            properties:
              events:
                description: List of events.
                type: array
                items:
                  $ref: '#/components/schemas/sync_rooms_state_events'
          timeline:
            $ref: '#/components/schemas/timeline'
          ephemeral:
            $ref: '#/components/schemas/list_of_event'
          account_data:
            $ref: '#/components/schemas/list_of_event'
          unread_notifications:
            $ref: '#/components/schemas/unread_notifications'
    list_of_event:
      type: object
      description: List of events.
      properties:
        events:
          type: array
          description: The timeline of messages and state changes in the room.
          items:
            $ref: '#/components/schemas/Event'
    unread_notifications:
      type: object
      description: Counts of unread notifications for this room
      properties:
        highlight_count:
          type: integer
          description: The number of unread notifications for this room with the highlight flag set
        notification_count:
          type: integer
          description: The total number of unread notifications for this room
    timeline:
      type: object
      description: The timeline of messages and state changes in the room.
      properties:
        limited:
          type: boolean
          description: '`True` if the number of events returned was limited by the limit on the filter.'
        prev_batch:
          type: string
          description: 'A token that can be supplied to the from parameter of the rooms /{roomId}/messages endpoint.'
        events:
          type: array
          items:
            type: object
            properties:
              content:
                type: object
                description: 'Fields in this object will vary depending on the type of event. When interacting with the REST API, this is the HTTP body.'
              type:
                type: string
                description: The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. `com.example.subdomain.event.type`
              event_id:
                type: string
                description: The globally unique event identifier.
              sender:
                type: string
                description: Contains the fully-qualified ID of the user who sent this event.
              origin_server_ts:
                type: integer
                description: Timestamp in milliseconds on originating homeserver when this event was sent.
              unsigned:
                $ref: '#/components/schemas/UnsignedData'
    sync_rooms_state_events:
      type: object
      properties:
        content:
          type: object
          description: 'Fields in this object will vary depending on the type of event. When interacting with the REST API, this is the HTTP body.'
        type:
          type: string
          description: The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. `com.example.subdomain.event.type`
        event_id:
          type: string
          description: The globally unique event identifier.
        sender:
          type: string
          description: Contains the fully-qualified ID of the user who sent this event.
        origin_server_ts:
          type: integer
          description: Timestamp in milliseconds on originating homeserver when this event was sent.
        state_key:
          type: string
          description: 'A unique key which defines the overwriting semantics for this piece of room state. This value is often a zero-length string. The presence of this key makes this event a State Event. State keys starting with an @ are reserved for referencing user IDs, such as room members. With the exception of a few events, state events set with a given user''s ID as the state key MUST only be set by that user.'
        unsigned:
          $ref: '#/components/schemas/UnsignedData'
        prev_content:
          type: object
          description: 'Optional. The previous content for this event. If there is no previous content, this key will be missing.'
    UnsignedData:
      type: object
      description: Contains optional extra information about the event.
      properties:
        age:
          type: integer
          description: 'The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.'
        transaction_id:
          type: string
          description: 'The client-supplied transaction ID, if the client being given the event is the same one which sent it.'
        redacted_because:
          description: 'Optional. The event that redacted this event, if any.'
          $ref: '#/components/schemas/Event'
    Event:
      type: object
      properties:
        content:
          type: object
          description: 'Fields in this object will vary depending on the type of event. When interacting with the REST API, this is the HTTP body.'
        type:
          type: string
          description: The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. `com.example.subdomain.event.type`
    sync_rooms_invite:
      type: object
      description: 'The state of a room that the user has been invited to. These state events may only have the sender, type, state_key and content keys present. These events do not replace any state that the client already has for the room, for example if the client has archived the room. Instead the client should keep two separate copies of the `state:` the one from the invite_state and one from the archived state. If the client joins the room then the current state will be given as a delta against the archived state not the invite_state.'
      properties:
        invite_state:
          $ref: '#/components/schemas/invite_state'
    invite_state:
      type: object
      properties:
        events:
          type: array
          description: array of StrippedState
          items:
            $ref: '#/components/schemas/StrippedState'
    StrippedState:
      type: object
      description: The StrippedState events that form the invite state.
      properties:
        content:
          $ref: '#/components/schemas/EventContent'
          description: Required. The content for the event.
        state_key:
          type: string
          description: Required. The state_key for the event.
        type:
          type: string
          description: Required. The type for the event.
        sender:
          type: string
          description: Required. The sender for the event.
      required:
        - content
        - state_key
        - type
        - sender
    EventContent:
      type: object
      properties:
        avatar_url:
          type: string
          description: 'The avatar URL for this user, if any. This is added by the homeserver.'
        displayname:
          type: string
          nullable: true
          description: 'The display name for this user, if any. This is added by the homeserver.'
        membership:
          enum:
            - invite
            - join
            - knock
            - leave
            - ban
          description: The membership state of the user.
        is_direct:
          type: boolean
          description: Flag indicating if the room containing this event was created with the intention of being a direct chat. See Direct Messaging.
        third_party_invite:
          $ref: '#/components/schemas/Invite'
        unsigned:
          $ref: '#/components/schemas/UnsignedData'
    Invite:
      type: object
      properties:
        display_name:
          type: string
          description: A name which can be displayed to represent the user instead of their third party identifier
        signed:
          $ref: '#/components/schemas/signed'
          
    signed:
      type: object
      description: A block of content which has been signed, which servers can use to verify the event. Clients should ignore this.
      properties:
        mxid:
          type: string
          description: The invited matrix user ID. Must be equal to the user_id property of the event.
          
        signatures:
          type: object
          description: A single signature from the verifying server, in the format specified by the Signing Events section of the server-server API.
          
        token:
          type: string
          description: The token property of the containing third_party_invite object.
    
    
    
    sync_rooms_leave:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/list_of_event'
        timeline:
          $ref: '#/components/schemas/timeline'
        account_data:
          $ref: '#/components/schemas/sync_account_data'
    sync_account_data:
      $ref: '#/components/schemas/list_of_event'
    sync_presence:
      $ref: '#/components/schemas/list_of_event'
    sync_response:
      type: object
      description: The initial snapshot or delta for the client to use to update their state.
      properties:
        next_batch:
          type: string
          description: The batch token to supply in the ``since`` param of the next `/sync` request.
        rooms:
          $ref: '#/components/schemas/sync_rooms'
        presence:
          $ref: '#/components/schemas/sync_presence'
        account_data:
          $ref: '#/components/schemas/sync_account_data'
        to_device:
          title: ToDevice
          type: object
          properties: {}
          description: 'Information on the send-to-device messages for the client device, as defined in |send_to_device_sync|.'
        device_lists:
          title: DeviceLists
          type: object
          description: 'Information on end-to-end device updates, as specified in |device_lists_sync|.'
          properties:
            changed:
              type: array
              items:
                type: string
            left:
              type: array
              items:
                type: string
        device_one_time_keys_count:
          title: One-time keys count
          type: object
          additionalProperties:
            type: integer
            description: 'Information on end-to-end encryption keys, as specified in |device_lists_sync|.'
  
  
  
  securitySchemes:
    accessToken:
      type: apiKey
      description: The access_token returned by a call to `/login` or `/register`
      name: access_token
      in: query
